# This file contains configuration for building the containers
---

version: '3.6'

services:
  nginx-php-moodle:
    build:
      args:
        PHP_VERSION: "${PHP_VERSION}"
      context: ./nginx-php-moodle
