# This file contains configuration for building the containers

services:
  nginx-php-moodle:
    build:
      args:
        MOODLE_TRACK: "${MOODLE_TRACK}"
        MOODLE_VERSION: "${MOODLE_VERSION}"
        NGINX_VERSION: "${NGINX_VERSION}"
        ONELOGIN_PLUGIN_VER: "${ONELOGIN_PLUGIN_VER}"
        PHP_VERSION: "${PHP_VERSION}"
      context: ./nginx-php-moodle
