---

version: '3.6'

services:
  deb-build:
    command:
      # source
      - '--input-type'
      - 'dir'
      # target type
      - "--output-type"
      - "deb"
      # DEB file name
      - "--package"
      - "/package/moodle-docker-${PHP_VERSION}-${MOODLE_VERSION}.deb"
      # package name
      - "--name"
      - "moodle-docker"
      #
      - "--version"
      - "${PHP_VERSION}-${MOODLE_VERSION}"
      #
      - "--deb-changelog"
      - "CHANGELOG.md"
      #
      - "--license"
      - "MIT"
      #
      - "--vendor"
      - "Security Compass <devops@securitycompass.com>"
      #
      - "--category"
      - "web"
      #
      - "--maintainer"
      - "Security Compass <devops@securitycompass.com>"
      #
      - "--category"
      - "web"
      #
      - "--deb-priority"
      - "optional"
      #
      - "--description"
      - "Moodle deployment using Docker"
      #
      - "--url"
      - "https://www.securitycompass.com/"
      # Package dependencies
      - "--depends"
      - "docker-ce > 18"
      # Overwrite existing DEB file
      - "--force"
      # Enables INFO output
      - "--verbose"
      # Files to package
      - "/package/conf=/etc/moodle"
      - "/package/dc.prod.yml=/etc/moodle"
      - "/package/dc.prod-dbonly.yml=/etc/moodle"
      - "/package/docker-compose.yml=/etc/moodle"
    environment:
      MOODLE_VERSION: "${MOODLE_VERSION}"
      PHP_VERSION: "${PHP_VERSION}"
    image: fpm:deb
    volumes:
      - type: bind
        source: ${PWD}
        target: /package
